package xyz.erupt.ai_canvas.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import xyz.erupt.ai.model.LLM;
import xyz.erupt.ai_canvas.handler.AiCanvasMenuHandler;
import xyz.erupt.ai_canvas.proxy.AiCanvasDataProxy;
import xyz.erupt.annotation.Erupt;
import xyz.erupt.annotation.EruptField;
import xyz.erupt.annotation.EruptI18n;
import xyz.erupt.annotation.config.QueryExpression;
import xyz.erupt.annotation.constant.AnnotationConst;
import xyz.erupt.annotation.sub_erupt.OpenWay;
import xyz.erupt.annotation.sub_erupt.RowOperation;
import xyz.erupt.annotation.sub_erupt.Tpl;
import xyz.erupt.annotation.sub_field.*;
import xyz.erupt.annotation.sub_field.sub_edit.BoolType;
import xyz.erupt.annotation.sub_field.sub_edit.InputType;
import xyz.erupt.annotation.sub_field.sub_edit.Search;
import xyz.erupt.jpa.model.MetaModelUpdateVo;
import xyz.erupt.upms.model.input.MenuPublishModal;

import java.util.Set;

/**
 * An AI generated view over one or more data models, built conversationally in
 * the designer: describe the page, iterate over versions. Bindings live in
 * {@link AiCanvasModel} rows edited as MULTI_FORM blocks; they may be extended
 * later (e.g. to pull in a related model), the current page source stays the
 * single source of truth for what past rounds produced.
 * Page sources live in {@link AiCanvasVersion} rows; this entity only points at
 * them: activeVersion is the designer's working draft, publishVersion is what
 * {@code AiCanvasController} serves to viewers.
 *
 * @author YuePeng
 * date 2026/8/3
 */
@Erupt(
        name = "AI Canvas",
        dataProxy = AiCanvasDataProxy.class,
        rowOperation = {
                @RowOperation(title = "Designer", icon = "fa fa-paint-brush",
                        mode = RowOperation.Mode.SINGLE, type = RowOperation.Type.TPL,
                        tpl = @Tpl(path = "/ai/canvas/design/{code}", openWay = OpenWay.ROUTER)),
                @RowOperation(title = "Send to Menu", icon = "fa fa-send",
                        mode = RowOperation.Mode.SINGLE,
                        eruptClass = MenuPublishModal.class,
                        operationHandler = AiCanvasMenuHandler.class)
        }
)
@Table(name = "e_ai_canvas")
@Getter
@Setter
@Entity
@EruptI18n
public class AiCanvas extends MetaModelUpdateVo {

    /** Menu value of the designer table menu; permission key for the build APIs */
    public static final String MENU_VALUE = "AiCanvas";

    // Short unique identifier used in the access path, generated by AiCanvasDataProxy
    @Column(unique = true, length = 16)
    @EruptField(views = @View(title = "Code", width = "90px"))
    private String code;

    @EruptField(
            views = @View(title = "Name"),
            edit = @Edit(title = "Name", notNull = true,
                    inputType = @InputType(fullSpan = true),
                    search = @Search(operator = QueryExpression.LIKE))
    )
    private String name;

    // Data models the page reads from, one MULTI_FORM block per binding. EAGER:
    // generation runs on a detached copy in an async thread (generateAsync) and
    // always needs the bindings; a canvas binds only a handful of models
    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
    @JoinColumn(name = "canvas_id")
    @EruptField(
            views = @View(title = "Data Models"),
            edit = @Edit(title = "Data Models", notNull = true, type = EditType.MULTI_FORM)
    )
    private Set<AiCanvasModel> models;

    // Page style code from prompts/style.json, chosen in the designer
    @EruptField(
            views = @View(title = "Style", width = "110px")
    )
    private String style;

    // Chat model used for the next generation, chosen in the designer conversation
    // panel; null falls back to the default chat model
    @ManyToOne
    @JoinColumn(name = "llm_id", foreignKey = @ForeignKey(name = "none", value = ConstraintMode.NO_CONSTRAINT))
    private LLM llm;

    @Column(length = AnnotationConst.REMARK_LENGTH)
    @EruptField(
            views = @View(title = "Description", type = ViewType.HTML),
            edit = @Edit(title = "Description", type = EditType.TEXTAREA)
    )
    private String remark;

    // Working-draft version row id shown in the designer; NOT what viewers see
    private Long activeVersion;

    // Published version row id served to viewers; null until the first explicit publish
    private Long publishVersion;

    @EruptField(
            views = @View(title = "Enable"),
            edit = @Edit(title = "Enable", notNull = true,
                    boolType = @BoolType(trueText = "Enable", falseText = "Disable"))
    )
    private Boolean enable = true;

    // Full-screen viewer route filled by AiCanvasDataProxy; click opens a dialog preview
    @Transient
    @EruptField(views = @View(title = "Path", type = ViewType.LINK_DIALOG, width = "80px"))
    private String path;

}
