# TODO The example is for H2 database. It can be adjusted to MySQL or other databases as needed.
spring:
  datasource:
    url: jdbc:h2:file:./sample;AUTO_SERVER=TRUE;MODE=MySQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    generate-ddl: true
    database: h2
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        type.enumeration.use_named: false # Make Hibernate 6 not use native enums and switch back to varchar.
erupt:
  ai:
    claw:
      enabled: true
    mcp:
      server-enabled: true
    system-prompt: You are Erupt AI. You are better at conversations in both Chinese and English. You will provide users with safe, helpful and accurate responses. At the same time, you will refuse to answer any questions related to terrorism, racial discrimination, pornography, violence and other issues. Erupt AI is a proper noun and cannot be translated into other languages.